using SMP.Dominio.Model;
using System.Collections;
using System.Xml.Linq;

namespace SMP.Dominio.Controlador
{
	public class ControladorDadosEsus
	{

		public static long COD_SEXO_FEMININO = 1;
		public static long COD_RACACOR_INDIGENA = 5;
		public static long COD_BRASIL = 31;
		public static long COD_NACIONALIDADE_BRASILEIRA = 1;
		public static long COD_NACIONALIDADE_NATURALIZADO = 2;
		public static long COD_NACIONALIDADE_ESTRANGEIRO = 3;
		public Dictionary<string, long> ObterOpcoesNacionalidade()
		{
			return new Dictionary<string, long>()
			{
				{ "Brasileira", 1 },
				{ "Naturalizado", 2 },
				{ "Estrangeiro", 3 },
			};
		}
		public Dictionary<string, long> ObterOpcoesSexo()
		{
			return new Dictionary<string, long>()
			{
				{ "Masculino", 0 },
				{ "Feminino", 1 },
			};
		}

		public Dictionary<string, long> ObterOpcoesRacaCor()
		{
			return new Dictionary<string, long>()
			{
				{ "Branca", 1 },
				{ "Preta", 2 },
				{ "Amarela", 3 },
				{ "Parda", 4 },
				{ "Indígena", 5 },
				{ "Sem informação", 6 },
			};
		}
		public Dictionary<string, long> ObterOpcoesEtnia()
		{
			return new Dictionary<string, long>()
			{
				{ "ACONA (WAKONAS, NACONAS, JAKONA, ACORANES)", 1 },
				{ "AIKANA (AIKANA, MAS SAKA,TUBARAO)", 2 },
                #region ...
                { "AJURU", 3 },
				{ "AKUNSU (AKUNT''SU)", 4 },
				{ "AMANAYE", 5 },
				{ "AMONDAWA", 6 },
				{ "ANAMBE", 7 },
				{ "APARAI (APALAI)", 8 },
				{ "APIAKA (APIACA)", 9 },
				{ "APINAYE (APINAJE/APINAIE/APINAGE)", 10 },
				{ "APURINA (APORINA, IPURINA, IPURINA, IPURINAN)", 11 },
				{ "ARANA (ARACUAI DO VALE DO JEQUITINHONHA)", 12 },
				{ "ARAPASO (ARAPACO)", 13 },
				{ "ARARA DE RONDONIA (KARO, URUCU, URUKU)", 14 },
				{ "ARARA DO ACRE (SHAWANAUA, AMAWAKA)", 15 },
				{ "ARARA DO ARIPUANA (ARARA DO BEIRADAO/ARI-PUANA)", 16 },
				{ "ARARA DO PARA (UKARAGMA, UKARAMMA)", 17 },
				{ "ARAWETE (ARAUETE)", 18 },
				{ "ARIKAPU (ARICAPU, ARIKAPO, MASUBI, MAXUBI)", 19 },
				{ "ARIKEM (ARIQUEN, ARIQUEME, ARIKEME)", 20 },
				{ "ARIKOSE (ARICOBE)", 21 },
				{ "ARUA", 22 },
				{ "ARUAK (ARAWAK)", 23 },
				{ "ASHANINKA (KAMPA)", 24 },
				{ "ASURINI DO TOCANTINS (AKUAWA/AKWAWA)", 25 },
				{ "ASURINI DO XINGU (AWAETE)", 26 },
				{ "ATIKUM (ATICUM)", 27 },
				{ "AVA - CANOEIRO", 28 },
				{ "AWETI (AUETI/AUETO)", 29 },
				{ "BAKAIRI (KURA, BACAIRI)", 30 },
				{ "BANAWA YAFI (BANAWA, BANAWA-JAFI)", 31 },
				{ "BANIWA (BANIUA, BANIVA, WALIMANAI, WAKUENAI)", 32 },
				{ "BARA (WAIPINOMAKA)", 33 },
				{ "BARASANA (HANERA)", 34 },
				{ "BARE", 35 },
				{ "BORORO (BOE)", 36 },
				{ "BOTOCUDO (GEREN)", 37 },
				{ "CANOE", 38 },
				{ "CASSUPA", 39 },
				{ "CHAMACOCO", 40 },
				{ "CHIQUITANO (XIQUITANO)", 41 },
				{ "CIKIYANA (SIKIANA)", 42 },
				{ "CINTA LARGA (MATETAMAE)", 43 },
				{ "COLUMBIARA (CORUMBIARA)", 44 },
				{ "DENI", 45 },
				{ "DESANA (DESANA, DESANO, DESSANO, WIRA, UMUKOMASA)", 46 },
				{ "DIAHUI (JAHOI, JAHUI, DIARROI)", 47 },
				{ "ENAWENE-NAWE (SALUMA)", 48 },
				{ "FULNI-O", 49 },
				{ "GALIBI (GALIBI DO OIAPOQUE, KARINHA)", 50 },
				{ "GALIBI MARWORNO (GALIBI DO UACA, ARUA)", 51 },
				{ "GAVIAO DE RONDONIA (DIGUT)", 52 },
				{ "GAVIAO KRIKATEJE", 53 },
				{ "GAVIAO PARKATEJE (PARKATEJE)", 54 },
				{ "GAVIAO PUKOBIE (PUKOBIE, PYKOPJE, GAVIAO DO MARANHAO)", 55 },
				{ "GUAJA (AWA, AVA)", 56 },
				{ "GUAJAJARA (TENETEHARA)", 57 },
				{ "GUARANI KAIOWA (PAI TAVYTERA)", 58 },
				{ "GUARANI M''BYA", 59 },
				{ "GUARANI NANDEVA (AVAKATUETE, CHIRIPA,NHANDEWA, AVA GUARANI)", 60 },
				{ "GUATO", 61 },
				{ "HIMARIMA (HIMERIMA)", 62 },
				{ "INGARIKO (INGARICO, AKAWAIO, KAPON)", 63 },
				{ "IRANXE (IRANTXE)", 64 },
				{ "ISSE", 65 },
				{ "JABOTI (JABUTI, KIPIU, YABYTI)", 66 },
				{ "JAMAMADI (YAMAMADI, DJEOROMITXI)", 67 },
				{ "JARAWARA", 68 },
				{ "JIRIPANCO (JERIPANCO, GERIPANCO)", 69 },
				{ "JUMA (YUMA)", 70 },
				{ "JURUNA", 71 },
				{ "JURUTI (YURITI)", 72 },
				{ "KAAPOR (URUBU-KAAPOR, KA''APOR, KAAPORTE)", 73 },
				{ "KADIWEU (CADUVEO, CADIUEU)", 74 },
				{ "KAIABI (CAIABI, KAYABI)", 75 },
				{ "KAIMBE (CAIMBE)", 76 },
				{ "KAINGANG (CAINGANGUE)", 77 },
				{ "KAIXANA (CAIXANA)", 78 },
				{ "KALABASSA (CALABASSA, CALABACAS)", 79 },
				{ "KALANCO", 80 },
				{ "KALAPALO (CALAPALO)", 81 },
				{ "KAMAYURA (CAMAIURA, KAMAIURA)", 82 },
				{ "KAMBA (CAMBA)", 83 },
				{ "KAMBEBA (CAMBEBA, OMAGUA)", 84 },
				{ "KAMBIWA (CAMBIUA)", 85 },
				{ "KAMBIWA PIPIPA (PIPIPA)", 86 },
				{ "KAMPE", 87 },
				{ "KANAMANTI (KANAMATI, CANAMANTI)", 88 },
				{ "KANAMARI (CANAMARI, KANAMARY, TUKUNA)", 89 },
				{ "KANELA APANIEKRA (CANELA)", 90 },
				{ "KANELA RANKOKAMEKRA (CANELA)", 91 },
				{ "KANINDE", 92 },
				{ "KANOE (CANOE)", 93 },
				{ "KANTARURE (CANTARURE)", 94 },
				{ "KAPINAWA (CAPINAUA)", 95 },
				{ "KARAJA (CARAJA)", 96 },
				{ "KARAJA/JAVAE (JAVAE)", 97 },
				{ "KARAJA/XAMBIOA (KARAJA DO NORTE)", 98 },
				{ "KARAPANA (CARAPANA, MUTEAMASA, UKOPINOPONA)", 99 },
				{ "KARAPOTO (CARAPOTO)", 100 },
				{ "KARIPUNA (CARIPUNA)", 101 },
				{ "KARIPUNA DO AMAPA (CARIPUNA)", 102 },
				{ "KARIRI (CARIRI)", 103 },
				{ "KARIRI-XOCO (CARIRI-CHOCO)", 104 },
				{ "KARITIANA (CARITIANA)", 105 },
				{ "KATAWIXI (KATAUIXI,KATAWIN, KATAWISI, CATAUICHI)", 106 },
				{ "KATUENA (CATUENA, KATWENA)", 107 },
				{ "KATUKINA (PEDA DJAPA)", 108 },
				{ "KATUKINA DO ACRE", 109 },
				{ "KAXARARI (CAXARARI)", 110 },
				{ "KAXINAWA (HUNI-KUIN, CASHINAUA, CAXINAUA)", 111 },
				{ "KAXIXO", 112 },
				{ "KAXUYANA (CAXUIANA)", 113 },
				{ "KAYAPO (CAIAPO)", 114 },
				{ "KAYAPO KARARAO (KARARAO)", 115 },
				{ "KAYAPO TXUKAHAMAE (TXUKAHAMAE)", 116 },
				{ "KAYAPO XICRIM (XIKRIN)", 117 },
				{ "KAYUISANA (CAIXANA, CAUIXANA, KAIXANA)", 118 },
				{ "KINIKINAWA (GUAN, KOINUKOEN, KINIKINAO)", 119 },
				{ "KIRIRI", 120 },
				{ "KOCAMA (COCAMA, KOKAMA)", 121 },
				{ "KOKUIREGATEJE", 122 },
				{ "KORUBO", 123 },
				{ "KRAHO (CRAO, KRAO)", 124 },
				{ "KREJE (KRENYE)", 125 },
				{ "KRENAK (BORUN, CRENAQUE)", 126 },
				{ "KRIKATI (KRINKATI)", 127 },
				{ "KUBEO (CUBEO, COBEWA, KUBEWA, PAMIWA, CUBEU)", 128 },
				{ "KUIKURO (KUIKURU, CUICURO)", 129 },
				{ "KUJUBIM (KUYUBI, CUJUBIM)", 130 },
				{ "KULINA PANO (CULINA)", 131 },
				{ "KULINA/MADIHA (CULINA, MADIJA, MADIHA)", 132 },
				{ "KURIPAKO (CURIPACO, CURRIPACO, CORIPACO, WAKUENAI)", 133 },
				{ "KURUAIA (CURUAIA)", 134 },
				{ "KWAZA (COAIA, KOAIA)", 135 },
				{ "MACHINERI (MANCHINERI, MANXINERI)", 136 },
				{ "MACURAP (MAKURAP)", 137 },
				{ "MAKU DOW (DOW)", 138 },
				{ "MAKU HUPDA (HUPDA)", 139 },
				{ "MAKU NADEB (NADEB)", 140 },
				{ "MAKU YUHUPDE (YUHUPDE)", 141 },
				{ "MAKUNA (MACUNA, YEBA-MASA)", 142 },
				{ "MAKUXI (MACUXI, MACHUSI, PEMON)", 143 },
				{ "MARIMAM (MARIMA)", 144 },
				{ "MARUBO", 145 },
				{ "MATIPU", 146 },
				{ "MATIS", 147 },
				{ "MATSE (MAYORUNA)", 148 },
				{ "MAXAKALI (MAXACALI)", 149 },
				{ "MAYA (MAYA)", 150 },
				{ "MAYTAPU", 151 },
				{ "MEHINAKO (MEINAKU, MEINACU)", 152 },
				{ "MEKEN (MEQUEM, MEKHEM, MICHENS)", 153 },
				{ "MENKY (MYKY, MUNKU, MENKI, MYNKY)", 154 },
				{ "MIRANHA (MIRANHA, MIRANA)", 155 },
				{ "MIRITI TAPUIA (MIRITI-TAPUYA, BUIA-TAPUYA)", 156 },
				{ "MUNDURUKU (MUNDURUCU)", 157 },
				{ "MURA", 158 },
				{ "NAHUKWA (NAFUQUA)", 159 },
				{ "NAMBIKWARA DO CAMPO (HALOTESU, KITHAULU, WAKALITESU, SAWENTES, MANDUKA)", 160 },
				{ "NAMBIKWARA DO NORTE (NEGAROTE ,MAMAINDE, LATUNDE, SABANE E MANDUKA, TAWANDE)", 161 },
				{ "NAMBIKWARA DO SUL (WASUSU ,HAHAINTESU, ALANTESU, WAIKISU, ALAKETESU, WASUSU, SARARE)", 162 },
				{ "NARAVUTE (NARUVOTO)", 163 },
				{ "NAWA (NAUA)", 164 },
				{ "NUKINI (NUQUINI, NUKUINI)", 165 },
				{ "OFAIE (OFAYE-XAVANTE)", 166 },
				{ "ORO WIN", 167 },
				{ "PAIAKU (JENIPAPO-KANINDE)", 168 },
				{ "PAKAA NOVA (WARI, PACAAS NOVOS)", 169 },
				{ "PALIKUR (AUKWAYENE, AUKUYENE, PALIKU''ENE)", 170 },
				{ "PANARA (KRENHAKARORE , KRENAKORE, KRENA-KARORE)", 171 },
				{ "PANKARARE (PANCARARE)", 172 },
				{ "PANKARARU (PANCARARU)", 173 },
				{ "PANKARARU KALANKO (KALANKO)", 174 },
				{ "PANKARARU KARUAZU (KARUAZU)", 175 },
				{ "PANKARU (PANCARU)", 176 },
				{ "PARAKANA (PARACANA, APITEREWA, AWAETE)", 177 },
				{ "PARECI (PARESI, HALITI)", 178 },
				{ "PARINTINTIN", 179 },
				{ "PATAMONA (KAPON)", 180 },
				{ "PATAXO", 181 },
				{ "PATAXO HA-HA-HAE", 182 },
				{ "PAUMARI (PALMARI)", 183 },
				{ "PAUMELENHO", 184 },
				{ "PIRAHA (MURA PIRAHA)", 185 },
				{ "PIRATUAPUIA (PIRATAPUYA, PIRATAPUYO, PIRA-TAPUYA, WAIKANA)", 186 },
				{ "PITAGUARI", 187 },
				{ "POTIGUARA", 188 },
				{ "POYANAWA (POIANAUA)", 189 },
				{ "RIKBAKTSA (CANOEIROS, ERIGPAKTSA)", 190 },
				{ "SAKURABIAT(MEKENS, SAKIRABIAP, SAKIRABIAR)", 191 },
				{ "SATERE-MAWE (SATERE-MAUE)", 192 },
				{ "SHANENAWA (KATUKINA)", 193 },
				{ "SIRIANO (SIRIA-MASA)", 194 },
				{ "SURIANA", 195 },
				{ "SURUI DE RONDONIA (PAITER)", 196 },
				{ "SURUI DO PARA (AIKEWARA)", 197 },
				{ "SUYA (SUIA/KISEDJE)", 198 },
				{ "TAPAYUNA (BEICO-DE-PAU)", 199 },
				{ "TAPEBA", 200 },
				{ "TAPIRAPE (TAPI''IRAPE)", 201 },
				{ "TAPUIA (TAPUIA-XAVANTE, TAPUIO)", 202 },
				{ "TARIANO (TARIANA, TALIASERI)", 203 },
				{ "TAUREPANG (TAULIPANG, PEMON, AREKUNA, PAGEYN)", 204 },
				{ "TEMBE", 205 },
				{ "TENHARIM", 206 },
				{ "TERENA", 207 },
				{ "TICUNA (TIKUNA, TUKUNA, MAGUTA)", 208 },
				{ "TINGUI BOTO", 209 },
				{ "TIRIYO EWARHUYANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)", 210 },
				{ "TIRIYO KAH''YANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)", 211 },
				{ "TIRIYO TSIKUYANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)", 212 },
				{ "TORA", 213 },
				{ "TREMEMBE", 214 },
				{ "TRUKA", 215 },
				{ "TRUMAI", 216 },
				{ "TSOHOM DJAPA (TSUNHUM-DJAPA)", 217 },
				{ "TUKANO (TUCANO, YE''PA-MASA, DASEA)", 218 },
				{ "TUMBALALA", 219 },
				{ "TUNAYANA", 220 },
				{ "TUPARI", 221 },
				{ "TUPINAMBA", 222 },
				{ "TUPINIQUIM", 223 },
				{ "TURIWARA", 224 },
				{ "TUXA", 225 },
				{ "TUYUKA (TUIUCA, DOKAPUARA, UTAPINOMAKAPHONA)", 226 },
				{ "TXIKAO (TXICAO, IKPENG)", 227 },
				{ "UMUTINA (OMOTINA, BARBADOS)", 228 },
				{ "URU-EU-WAU-WAU (URUEU-UAU-UAU, URUPAIN, URUPA)", 229 },
				{ "WAI WAI HIXKARYANA (HIXKARYANA)", 230 },
				{ "WAI WAI KARAFAWYANA (KARAFAWYANA, KARA-PAWYANA)", 231 },
				{ "WAI WAI XEREU (XEREU)", 232 },
				{ "WAI WAI KATUENA (KATUENA)", 233 },
				{ "WAI WAI MAWAYANA (MAWAYANA)", 234 },
				{ "WAIAPI (WAYAMPI, OYAMPI, WAYAPY, )", 235 },
				{ "WAIMIRI ATROARI (KINA)", 236 },
				{ "WANANO (UANANO, WANANA)", 237 },
				{ "WAPIXANA (UAPIXANA, VAPIDIANA, WAPISIANA, WAPISHANA)", 238 },
				{ "WAREKENA (UAREQUENA, WEREKENA)", 239 },
				{ "WASSU", 240 },
				{ "WAURA (UAURA, WAUJA)", 241 },
				{ "WAYANA (WAIANA, UAIANA)", 242 },
				{ "WITOTO (UITOTO, HUITOTO)", 243 },
				{ "XAKRIABA (XACRIABA)", 244 },
				{ "XAVANTE (A''UWE, AKWE, AWEN, AKWEN)", 245 },
				{ "XERENTE (AKWE, AWEN, AKWEN)", 246 },
				{ "XETA", 247 },
				{ "XIPAIA (SHIPAYA, XIPAYA)", 248 },
				{ "XOKLENG (SHOKLENG, XOCLENG)", 249 },
				{ "XOKO (XOCO, CHOCO)", 250 },
				{ "XUKURU (XUCURU)", 251 },
				{ "XUKURU KARIRI (XUCURU-KARIRI)", 252 },
				{ "YAIPIYANA", 253 },
				{ "YAMINAWA (JAMINAWA, IAMINAWA)", 254 },
				{ "YANOMAMI NINAM (IANOMAMI, IANOAMA, XIRIANA)", 255 },
				{ "YANOMAMI SANUMA (IANOMAMI, IANOAMA, XIRIANA)", 256 },
				{ "YANOMAMI YANOMAM (IANOMAMI, IANOAMA, XIRIANA)", 257 },
				{ "YAWALAPITI (IAUALAPITI)", 258 },
				{ "YAWANAWA (IAUANAUA)", 259 },
				{ "YEKUANA (MAIONGON, YE''KUANA, YEKWANA, MAYONGONG)", 260 },
				{ "YUDJA (JURUNA, YURUNA)", 261 },
				{ "ZO''E (POTURU)", 262 },
				{ "ZORO (PAGEYN)", 263 },
				{ "ZURUAHA (SOROWAHA, SURUWAHA)", 264 },
                #endregion
           };
		}

		public Dictionary<string, long> ObterOpcoesRelacaoParentesco()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "Cônjuge / Companheiro(a)", 137 },
				{ "Filho(a)", 138 },
				{ "Enteado(a)", 139 },
				{ "Neto(a) / Bisneto(a)", 140 },
				{ "Pai / Mãe", 141 },
				{ "Sogro(a)", 142 },
				{ "Irmão / Irmã", 143 },
				{ "Genro / Nora", 144 },
				{ "Outro parente", 145 },
				{ "Não parente", 146 },
			};

			return lista;
		}

		public Dictionary<string, long> ObterOpcoesGrauInstrucao()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "Creche", 51 },
				{ "Pré-escola (exceto CA)", 52 },
				{ "Classe de alfabetização - CA", 53 },
				{ "Ensino fundamental 1ª a 4ª séries", 54 },
				{ "Ensino fundamental 5ª a 8ª séries", 55 },
				{ "Ensino fundamental completo", 56 },
				{ "Ensino fundamental especial", 61 },
				{ "Ensino fundamental EJA - séries iniciais (supletivo 1ª a 4ª)", 58 },
				{ "Ensino fundamental EJA - séries finais (supletivo 5ª a 8ª)", 59 },
				{ "Ensino médio, médio 2º ciclo (científico, técnico e etc)", 60 },
				{ "Ensino médio especial", 57 },
				{ "Ensino médio EJA (supletivo)", 62 },
				{ "Superior, aperfeiçoamento, especialização, mestrado, doutorado", 63 },
				{ "Alfabetização para adultos (Mobral, etc)", 64 },
				{ "Nenhum", 65 },
			};

			return lista;
		}

		public Dictionary<string, long> ObterOpcoesSituacaoMercado()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "Empregador", 66 },
				{ "Assalariado com carteira de trabalho", 67 },
				{ "Assalariado sem carteira de trabalho", 68 },
				{ "Autônomo com previdência social", 69 },
				{ "Autônomo sem previdência social", 70 },
				{ "Aposentado / Pensionista", 71 },
				{ "Desempregado", 72 },
				{ "Não trabalha", 73 },
				{ "Servidor público / Militar", 147 },
				{ "Outro", 74 },
			};

			return lista;
		}

		public Dictionary<string, long> ObterOpcoesResponsavelPorCrianca()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "Adulto responsável", 1 },
				{ "Outra(s) criança(s)", 2 },
				{ "Adolescente", 133 },
				{ "Sozinha", 3 },
				{ "Creche", 134 },
				{ "Outro", 4 },
			};

			return lista;
		}

		public string ObterDescricaoQualDeficiencia(string listaDeficiencias)
		{
			List<string> retorno = new List<string>();
			var lista = ObterOpcoesDeficiencias();

			foreach (var item in lista.Where(d => Utilitarios.ConvertToList<long>(listaDeficiencias).Contains(d.Codigo)).ToList())
			{
				retorno.Add(item.Descricao);
			}

			return Utilitarios.ConvertFromList(retorno);
		}

		public List<DeficienciaModel> ObterOpcoesDeficiencias()
		{
			List<DeficienciaModel> lista = new List<DeficienciaModel>()
			{
				new DeficienciaModel("Auditiva", 12),
				new DeficienciaModel("Visual", 13),
				new DeficienciaModel("Intelectual / Cognitiva", 14),
				new DeficienciaModel("Física", 15),
				new DeficienciaModel("Outra", 16),
			};

			return lista;
		}

		public Dictionary<string, long>? ObterOpcoesConsideracaoPeso()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "Abaixo do peso", 21 },
				{ "Peso adequado", 22 },
				{ "Acima do peso", 23 },
			};

			return lista;
		}

		public Dictionary<string, long>? ObterOpcoesSituacaoVacinalCOVID19()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "Não Vacinado", 0 },
				{ "Vacinado - 1ª Dose", 1 },
				{ "Vacinado - 2ª Dose", 2 },
				{ "Vacinado - 3ª Dose", 3 },
				{ "Vacinado - 4ª Dose", 4 },
			};

			return lista;
		}

		public Dictionary<string, long>? ObterOpcoesPais()
		{
			Dictionary<string, long> lista = new Dictionary<string, long>()
			{
				{ "AFEGANISTÃO", 1 },
				{ "ÁFRICA DO SUL", 2 },
				{ "ALBÂNIA", 3 },
				#region ...
				{ "ALEMANHA", 4 },
				{ "ANDORRA", 5 },
				{ "ANGOLA", 6 },
				{ "ANGUILLA", 7 },
				{ "ANTÁRCTICA", 8 },
				{ "ANTIGUA E BARBUDA", 9 },
				{ "ANTILHAS HOLANDESAS", 10 },
				{ "ARÁBIA SAUDITA", 11 },
				{ "ARGÉLIA", 12 },
				{ "ARGENTINA", 13 },
				{ "ARMÊNIA", 14 },
				{ "ARUBA", 15 },
				{ "AUSTRÁLIA", 16 },
				{ "ÁUSTRIA", 17 },
				{ "AZERBAIDJÃO", 18 },
				{ "BAHAMAS", 19 },
				{ "BANGLADESH", 20 },
				{ "BARBADOS", 21 },
				{ "BAREIN", 22 },
				{ "BELARUS", 23 },
				{ "BÉLGICA", 24 },
				{ "BELIZE", 25 },
				{ "BENIN", 26 },
				{ "BERMUDA", 27 },
				{ "BOLÍVIA", 28 },
				{ "BÓSNIA E HERZEGÓVINA", 29 },
				{ "BOTSWANA", 30 },
				{ "BRASIL", 31 },
				{ "BRUNEI", 32 },
				{ "BULGÁRIA", 33 },
				{ "BURKINA FASSO", 34 },
				{ "BURUNDI", 35 },
				{ "BUTÃO", 36 },
				{ "CABO VERDE", 37 },
				{ "CAMARÕES", 38 },
				{ "CAMBOJA", 39 },
				{ "CANADÁ", 40 },
				{ "CATAR", 41 },
				{ "CAZAQUISTÃO", 42 },
				{ "CHADE", 43 },
				{ "CHILE", 44 },
				{ "CHINA", 45 },
				{ "CHIPRE", 46 },
				{ "CINGAPURA", 47 },
				{ "COLÔMBIA", 48 },
				{ "COMORES", 49 },
				{ "CONGO", 50 },
				{ "CORÉIA DO NORTE", 51 },
				{ "CORÉIA DO SUL", 52 },
				{ "COSTA DO MARFIM", 53 },
				{ "COSTA RICA", 54 },
				{ "CROÁCIA", 55 },
				{ "CUBA", 56 },
				{ "DINAMARCA", 57 },
				{ "DJIBUTI", 58 },
				{ "DOMINICA", 59 },
				{ "EGITO", 60 },
				{ "EL SALVADOR", 61 },
				{ "EMIRADOS ÁRABES UNIDOS", 62 },
				{ "EQUADOR", 63 },
				{ "ERITRÉIA", 64 },
				{ "ESLOVÁQUIA", 65 },
				{ "ESLOVÊNIA", 66 },
				{ "ESPANHA", 67 },
				{ "ESTADOS UNIDOS", 68 },
				{ "ESTÔNIA", 69 },
				{ "ETIÓPIA", 70 },
				{ "FEDERAÇÃO RUSSA", 71 },
				{ "FIJI", 72 },
				{ "FILIPINAS", 73 },
				{ "FINLÂNDIA", 74 },
				{ "FRANÇA", 75 },
				{ "FRANÇA METROPOLITANA", 76 },
				{ "GABÃO", 77 },
				{ "GÂMBIA", 78 },
				{ "GANA", 79 },
				{ "GEÓRGIA", 80 },
				{ "GIBRALTAR", 81 },
				{ "GRÃ-BRETANHA", 82 },
				{ "GRANADA", 83 },
				{ "GRÉCIA", 84 },
				{ "GROENLÂNDIA", 85 },
				{ "GUADALUPE", 86 },
				{ "GUAM", 87 },
				{ "GUATEMALA", 88 },
				{ "GUIANA", 89 },
				{ "GUIANA FRANCESA", 90 },
				{ "GUINÉ", 91 },
				{ "GUINÉ EQUATORIAL", 92 },
				{ "GUINÉ-BISSAU", 93 },
				{ "HAITI", 94 },
				{ "HOLANDA", 95 },
				{ "HONDURAS", 96 },
				{ "HONG KONG", 97 },
				{ "HUNGRIA", 98 },
				{ "IÊMEN", 99 },
				{ "ILHA BOUVET", 100 },
				{ "ILHA CHRISTMAS", 101 },
				{ "ILHA NORFOLK", 102 },
				{ "ILHAS CAYMAN", 103 },
				{ "ILHAS COCOS", 104 },
				{ "ILHAS COOK", 105 },
				{ "ILHAS DE GUERNSEY", 106 },
				{ "ILHAS DE JERSEY", 107 },
				{ "ILHAS FAROE", 108 },
				{ "ILHAS GEÓRGIA DO SUL E ILHAS SANDWICH DO SUL", 109 },
				{ "ILHAS HEARD E MAC DONALD", 110 },
				{ "ILHAS MALVINAS", 111 },
				{ "ILHAS MARIANA", 112 },
				{ "ILHAS MARSHALL", 113 },
				{ "ILHAS PITCAIRN", 114 },
				{ "ILHAS REUNIÃO", 115 },
				{ "ILHAS SALOMÃO", 116 },
				{ "ILHAS SANTA HELENA", 117 },
				{ "ILHAS SVALBARD E JAN MAYEN", 118 },
				{ "ILHAS TOKELAU", 119 },
				{ "ILHAS TURKS E CAICOS", 120 },
				{ "ILHAS VIRGENS", 121 },
				{ "ILHAS VIRGENS BRITÂNICAS", 122 },
				{ "ILHAS WALLIS E FUTUNA", 123 },
				{ "ÍNDIA", 124 },
				{ "INDONÉSIA", 125 },
				{ "IRÃ", 126 },
				{ "IRAQUE", 127 },
				{ "IRLANDA", 128 },
				{ "ISLÂNDIA", 129 },
				{ "ISRAEL", 130 },
				{ "ITÁLIA", 131 },
				{ "IUGOSLÁVIA", 132 },
				{ "JAMAICA", 133 },
				{ "JAPÃO", 134 },
				{ "JORDÂNIA", 135 },
				{ "KIRIBATI", 136 },
				{ "KUWEIT", 137 },
				{ "LAOS", 138 },
				{ "LESOTO", 139 },
				{ "LETÔNIA", 140 },
				{ "LÍBANO", 141 },
				{ "LIBÉRIA", 142 },
				{ "LÍBIA", 143 },
				{ "LIECHTENSTEIN", 144 },
				{ "LITUÂNIA", 145 },
				{ "LUXEMBURGO", 146 },
				{ "MACAU", 147 },
				{ "MACEDÔNIA", 148 },
				{ "MADAGASCAR", 149 },
				{ "MALÁSIA", 150 },
				{ "MALAUÍ", 151 },
				{ "MALDIVAS", 152 },
				{ "MALI", 153 },
				{ "MALTA", 154 },
				{ "MARROCOS", 155 },
				{ "MARTINICA", 156 },
				{ "MAURÍCIO", 157 },
				{ "MAURITÂNIA", 158 },
				{ "MAYOTTE", 159 },
				{ "MÉXICO", 160 },
				{ "MIANMAR", 161 },
				{ "MICRONÉSIA", 162 },
				{ "MOÇAMBIQUE", 163 },
				{ "MOLDÁVIA", 164 },
				{ "MÔNACO", 165 },
				{ "MONGÓLIA", 166 },
				{ "MONTSERRAT", 167 },
				{ "NAMÍBIA", 168 },
				{ "NAURU", 169 },
				{ "NEPAL", 170 },
				{ "NICARÁGUA", 171 },
				{ "NIGER", 172 },
				{ "NIGÉRIA", 173 },
				{ "NIUE", 174 },
				{ "NORUEGA", 175 },
				{ "NOVA CALEDÔNIA", 176 },
				{ "NOVA ZELÂNDIA", 177 },
				{ "OMÃ", 178 },
				{ "PALAU", 179 },
				{ "PANAMÁ", 180 },
				{ "PAPUA NOVA GUINÉ", 181 },
				{ "PAQUISTÃO", 182 },
				{ "PARAGUAI", 183 },
				{ "PERU", 184 },
				{ "POLINÉSIA FRANCESA", 185 },
				{ "POLÔNIA", 186 },
				{ "PORTO RICO", 187 },
				{ "PORTUGAL", 188 },
				{ "QUÊNIA", 189 },
				{ "QUIRGUÍZIA", 190 },
				{ "REPÚBLICA CENTRO-AFRICANA", 191 },
				{ "REPÚBLICA DOMINICANA", 192 },
				{ "REPÚBLICA TCHECA", 193 },
				{ "ROMÊNIA", 194 },
				{ "RUANDA", 195 },
				{ "SAHARA OCIDENTAL", 196 },
				{ "SAMOA AMERICANA", 197 },
				{ "SAMOA OCIDENTAL", 198 },
				{ "SAN MARINO", 199 },
				{ "SANTA LÚCIA", 200 },
				{ "SÃO CRISTÓVÃO E NÉVIS", 201 },
				{ "SÃO PIERRE E MIQUELON", 202 },
				{ "SÃO TOMÉ E PRÍNCIPE", 203 },
				{ "SÃO VICENTE E GRANADINAS", 204 },
				{ "SEICHELES", 205 },
				{ "SENEGAL", 206 },
				{ "SERRA LEOA", 207 },
				{ "SÍRIA", 208 },
				{ "SOMÁLIA", 209 },
				{ "SRI LANKA", 210 },
				{ "SUAZILÂNDIA", 211 },
				{ "SUDÃO", 212 },
				{ "SUÉCIA", 213 },
				{ "SUÍÇA", 214 },
				{ "SURINAME", 215 },
				{ "TADJIQUISTÃO", 216 },
				{ "TAILÂNDIA", 217 },
				{ "TAIWAN", 218 },
				{ "TANZÂNIA", 219 },
				{ "TERRITÓRIOS FRANCESES MERIDIONAIS", 220 },
				{ "TIMOR LESTE", 221 },
				{ "TOGO", 222 },
				{ "TONGA", 223 },
				{ "TRINIDAD E TOBAGO", 224 },
				{ "TUNÍSIA", 225 },
				{ "TURCOMÊNIA", 226 },
				{ "TURQUIA", 227 },
				{ "TUVALU", 228 },
				{ "UCRÂNIA", 229 },
				{ "UGANDA", 230 },
				{ "URUGUAI", 231 },
				{ "UZBEQUISTÃO", 232 },
				{ "VANUATU", 233 },
				{ "VATICANO", 234 },
				{ "VENEZUELA", 235 },
				{ "VIETNÃ", 236 },
				{ "ZÂMBIA", 237 },
				{ "ZIMBÁBUE", 238 },
				{ "ILHAS GUERNSEY", 239 },
				{ "JERSEY", 240 },
				{ "MONTENEGRO", 241 },
				{ "ESTADO DA PALESTINA", 242 },
				{ "SÉRVIA", 243 },
				#endregion
			};

			return lista;
		}
	}
}
